guardian/prosemirror-typerighter

pages/dist/bundle.js, src/ts/index.ts, src/ts/interfaces/IValidation.ts, src/ts/services/ValidationAPIService.ts, src/ts/test/state.spec.ts, src/ts/utils/range.ts
A validation response should be a one-to-many relationship between a validation input and the corresponding outputs, but many inputs were added to the response. This led to odd behaviour. This PR fixes that issue.
=> Fix bug where multiple inputs did not map to outputs

pages/dist/bundle.js, pages/dist/styles.css, pages/index.ts, src/ts/components/ValidationControls.tsx, src/ts/components/ValidationOverlay.tsx, src/ts/components/ValidationSidebar.tsx, src/ts/createValidationPlugin.ts, src/ts/interfaces/IValidation.ts, src/ts/services/ValidationAPIService.ts, src/ts/state.ts, src/ts/store.ts, src/ts/test/__snapshots__/state.spec.ts.snap, src/ts/test/__snapshots__/validationAPIService.spec.ts.snap, src/ts/test/state.spec.ts, src/ts/test/validationAPIService.spec.ts, src/ts/utils/range.ts, src/ts/utils/types.ts
The validation response interface required a validation input. This PR removes that requirement by looking the input up by ID.
In doing so, there were a few quality of life improvements - 
- The state now models multiple validations-in-flight, each containing a single validation input, to allow multiple inputs to return at different times; this is an obvious but necessary change to allow services to return validations chunk by chunk
- Validations-in-flight now contain their own mapping, which is updated on every transaction. This removes the need for the transaction history that was maintained in the previous implementation.
=> Simplify validation response

package.json, pages/dist/bundle.js, pages/dist/worker.js, src/ts/adapters/interfaces/ILanguageTool.ts, src/ts/adapters/languageTool.ts, src/ts/adapters/regex.ts, src/ts/adapters/typerighter.ts, src/ts/createValidationPlugin.ts, src/ts/interfaces/IValidation.ts, src/ts/interfaces/IValidationAPIAdapter.ts, src/ts/services/ValidationAPIService.ts, src/ts/state.ts, src/ts/store.ts, src/ts/test/__snapshots__/validationAPIService.spec.ts.snap, src/ts/test/prosemirror.spec.ts, src/ts/test/range.spec.ts, src/ts/test/state.spec.ts, src/ts/test/store.spec.ts, src/ts/test/validationAPIService.spec.ts, src/ts/utils/decoration.ts, src/ts/utils/prosemirror.ts, src/ts/utils/range.ts, src/ts/utils/types.ts
When handling the output of validation services, this plugin cares about ranges and (at the moment) suggestions, but consuming code might have a different set of data to store against a validation output. This PR adds a type parameter for the validation output that extends a base output.
=> Genericise base validation object

package.json, src/ts/adapters/languageTool.ts, src/ts/adapters/regex.ts, src/ts/adapters/typerighter.ts, src/ts/createValidationPlugin.ts, src/ts/interfaces/IValidation.ts, src/ts/services/ValidationAPIService.ts, src/ts/state.ts, src/ts/test/__snapshots__/validationAPIService.spec.ts.snap, src/ts/test/helpers/fixtures.ts, src/ts/test/prosemirror.spec.ts, src/ts/test/state.spec.ts, src/ts/test/validationAPIService.spec.ts, src/ts/utils/prosemirror.ts, src/ts/utils/validation.ts, yarn.lock
This PR adds an ID to the validation input definition, which is the correct place to put it.
The ID is derived from the transaction timestamp and the range to which the input applies, which is a) deterministic and b) unique for each input.
This is nice, because it allows us to see the range at a glance when looking at logs etc., whilst keeping our action creators pure (no need for v4() or similar).
There are a few other changes in this PR that squash bugs relating to validation requests etc. -- as this is largely a one-person operation I lacked the discipline to split them out into a separate PR!
=> Refine validation inputs and outputs

src/css/index.scss
... because orange and slightly-more-orange isn't easy to distinguish, the inflight decorations are now green.
=> Clearer difference between pending and inflight debug decorations

pages/index.ts, src/css/index.scss, src/css/validationSidebarOutput.scss, src/ts/commands.ts, src/ts/components/Suggestion.tsx, src/ts/components/SuggestionList.tsx, src/ts/components/ValidationOutput.tsx, src/ts/components/ValidationOverlay.tsx, src/ts/components/ValidationSidebar.tsx, src/ts/components/ValidationSidebarOutput.tsx, src/ts/createView.tsx, src/ts/interfaces/IValidation.ts, src/ts/services/adapters/TyperighterAdapter.ts, src/ts/services/adapters/TyperighterWsAdapter.ts, src/ts/services/adapters/interfaces/ITyperighter.ts, src/ts/state/state.ts, src/ts/state/test/__snapshots__/state.spec.ts.snap, src/ts/state/test/state.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/test/validationAPIService.spec.ts, src/ts/utils/decoration.ts, src/ts/utils/validation.ts
Allow users to batch-apply suggestions if `autoApplyFirstSuggestion` is set on incoming rules.
Currently, there's no confirm step, but it's likely we'll want make the changes about to be applied clear to the user, and ask them to confirm, as although the normal rules for undo/redo apply, this  operation changes things the author isn't guaranteed to see.
There's also a minor refactor to user defined settings for an upcoming PR, as it's likely we'll want to toggle the availability of this feature.
=> Allow users to batch-apply suggestions

src/css/index.scss, src/ts/components/MatchOverlay.tsx, src/ts/createTyperighterPlugin.ts, src/ts/state/reducer.ts, src/ts/utils/dom.ts
This PR corrects tooltip positioning for decorations that break across lines. To solve this problem, we use `getClientRects()`, which returns the bounding boxes for each part of the decoration.
=> Correct tooltip positioning for decorations that break across lines

pages/dist/index.html
Adds the lovely [prosemirror-dev-tools](https://github.com/d4rkr00t/prosemirror-dev-tools) to the gh-pages index page.
=> Add devtools to pages html

pages/index.ts, src/css/SidebarMatch.scss, src/ts/components/Match.tsx, src/ts/components/SidebarMatch.tsx, src/ts/interfaces/IMatch.ts, src/ts/services/adapters/RegexAdapter.ts, src/ts/services/adapters/TyperighterAdapter.ts, src/ts/services/adapters/interfaces/ITyperighter.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/state/selectors.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/fixtures.ts
This PR adds matched text to the Matcher models, and display it in the sidebar matches, as so:
In future, we can imagine displaying a diff or 'old -> new' or similar.
=> Add matched text to the Matcher models, and display it in the sidebar matches.

package-lock.json, package.json, src/ts/commands.ts, src/ts/components/Controls.tsx, src/ts/components/Match.tsx, src/ts/components/Sidebar.tsx, src/ts/components/SidebarMatch.tsx, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx
_Co-authored-by: @SHession, @tjsilver_ 
Suggestions were removed in #64. This PR adds them back, and improves UI behaviour –
- When suggestions are applied, the tooltip they came from is closed.
- When the document is changed, matches touched by those changes are removed.
Launch the plugin and check the behaviours listed above occur for matches that have suggestions.
Examples from the current Guardian sheet include 'lowlives', which gives a single suggestion.
The behaviour above should be reflected in the UI.
=> Restore suggestion behaviour

package-lock.json, package.json
A [recent PR](https://github.com/guardian/prosemirror-typerighter/pull/69) upgraded rollup but broke CSS bundling in the process. This PR upgrades `rollup-plugin-scss`, which fixes the issue.
Run the build script. It should produce an `index.css` file in `./dist`. Linking the plugin to other projects with `npm link` should work as expected.
=> Fix CSS bundling

src/css/index.scss, src/ts/components/Match.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/Sidebar.tsx, src/ts/createView.tsx
Adds a link to the typerighter popup so allow the user to send feedback via a google form.
The google form has been set up to only accept entries from validated email addresses ending @guardian.co.uk, but is currently owned by Justin Rowles and should be owned by an internal account.
I... don't really know.  I ran composer locally and installed the plugin locally.
Clickable link with appropriate embedded metadata appears in popup.
Form sends email to typerighter@theguardian.com
=> Add feedback link

Brewfile, build/README.md, nginx/nginx-mapping.yaml, pages/index.ts, scripts/setup.sh, src/ts/services/adapters/TyperighterAdapter.ts
At the moment, this plugin makes `fetch` requests that only include `same-origin` cookies (the default for fetch). This is insufficient when pan-domain authentication is added to a Typerighter service – we'll need to use the `include` setting to send pan-domain cookies for authentication.
This also complicates local development, in that once auth is added, sending requests from a localhost address will fail. We'll need to send requests from a dev-gutools.co.uk address, a problem that's solved by at the Guardian by using [dev-nginx](https://github.com/guardian/dev-nginx) to create the relevant address and map it to a local server.
This PR adds cookies to the API fetch requests, an nginx mapping file, and a setup script to install dev-nginx, run it, and install JS deps in one step.
It also …
=> Make this plugin compatible with the Guardian's pan-domain authentication

src/css/index.scss, src/ts/components/Controls.tsx, src/ts/components/Match.tsx, src/ts/components/Sidebar.tsx
With the addition of feedback links to match overlays (https://github.com/guardian/prosemirror-typerighter/pull/75), the wording on the overlay and sidebar feedback links was confusing. The sidebar link is for issues with Typerighter in general, whereas the overlay link is for issues with a particular rule/result.
The link wording has been amended for clarity, and as part of that, the word 'Controls' has been renamed to 'Typerighter', so that users know that the sidebar is specific to the tool.
Run the branch locally and see the wording has changed. 
We receive feedback for the correct context, ie at tool-level or rule-level, as appropriate.
### After (NB link colour will be the same as in Composer images above, these screenshots were taken from Prosemirror Validator)
=> Improve contact link wording and styling

pages/dist/index.html, pages/index.ts, src/css/Controls.scss, src/css/Sidebar.scss, src/css/SidebarMatch.scss, src/css/Suggestion.scss, src/css/index.scss, src/ts/components/Controls.tsx, src/ts/components/Match.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/SidebarMatch.tsx, src/ts/createView.tsx
The UI for this plugin was looking a little frumpy. It's still a bit frumpy, but I've made a few changes –
- References to category colours are now represented by swatches or borders, to ensure the category text is always legible
- A bug which made it difficult to traverse from match to tooltip has been fixed
- The two panels are consolidated – I'm not sure there was a good reason to keep them separate
- Font sizes have been normalised into three variables to ensure things are consistent, and applied at the root with em sizing to ensure sizing is consistent when this UI is embedded elsewhere 
- A few spacing tweaks, also to keep things consistent
- The suggestion/replacement rendering has been moved to the top of the match tooltip, the bounding box of the suggestion is now clear from a …
=> Numerous styling changes

src/ts/createView.tsx, src/ts/utils/logger.ts
Adds an optional logging capability to the plugin.
https://trello.com/c/dU27JPiI/317-log-prosemirror-typerighter-errors-to-elk
Initial logging should be visible in the javascript console.
See logging.
N/A
N/A
=> Add logging capability

src/ts/commands.ts, src/ts/state/actions.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts
Adds a prosemirror command to ignore a match. Ignored matches are removed from the plugin state, along with their decorations.
PR for the relevant UI to follow.
There's no UI path to exercise this code yet, but the tests should give some confidence that it works as expected.
Issuing the `ignoreMatches` command removes matches and match decorations from the plugin state.
=> Add command to ignore matches

src/ts/utils/decoration.ts, src/ts/utils/test/decoration.spec.ts
This PR simply removes the `markAsCorrect` tick from matches where the suggestion perfectly matches the text. Instead it marks those matches as the currently used green colour #3ff200.
Check for matches on a phrase where the suggestion matches the word exactly, an example is Instagram. The decoration for this match should no longer include a tick, and should always appear green.
There is less noise on the document when checking for matches.
=> Remove tick from correct matches

src/ts/components/Controls.tsx, src/ts/createView.tsx, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/fixtures.ts
This PR stores the errors received over the course of a match request and allows a users to submit them to support. These errors are cleared out once a new request for matches is made. When an error occurs, a contact us message appears, this link has been changed to use the existing google form but provides error context instead of rule context.
The format for the error context is: 
```
{
"url": "https://typerighter-client.local.dev-gutools.co.uk/",
"errors": [
{
"requestId": "e0ebcce8-5489-4085-a2de-87c42d5af3e1",
"blockId": "1596720218960-from:16-to:972",
"message": "400: Bad Request",
"categoryIds": [
"Red",
"Blue",
"Green"
]
}
]
}
```
Up to ten error messages will be sent to the form, this is an arbitrary amount, designed to avoid the character limit on urls. 
Provide the google form …
=> Store all request errors

src/css/Controls.scss, src/css/Sidebar.scss, src/css/index.scss, src/ts/components/Controls.tsx
The 'Advanced' pane is not required at present, and with the coming categories/tags refactor, it doesn't present useful things to the user.
I've commented out the code relating to the 'Advanced' pane and any CSS that was only used by that code. I chose to comment out the code (a) in case it might be used in the future, and (b) because some of the code wrapped already-commented-out code, but can delete instead if preferred.
Run the branch locally and see that the 'Advanced' pane is no longer present.
=> Hide Advanced pane

src/ts/createView.tsx
#88 broke our test page – the logging param in `createView.tsx` should be optional. This PR fixes that.
`npm run watch` should work as expected.
=> Logging param in createView.tsx should be optional

build/rollup.common.js, build/rollup.config.build.js, build/rollup.config.dev.js, package.json, src/ts/components/Match.tsx
At the moment, `material-ui` is not bundled with our dist build. This means that our 'preact' aliasing doesn't work, which breaks the build.
This PR adds material UI directly to the bundle. It comes at a significant bundle cost – 67kb to ~458kb – which we should work to mitigate as a priority. It may be that material-ui is not a suitable candidate for inclusion.
Consume this plugin via e.g. `npm link` in a consumer project. It should work as expected.
=> Bundle material-ui with the dist build, ignoring other modules

src/ts/commands.ts, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx, src/ts/state/actions.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/test/helpers/prosemirror.ts
Adds an 'isActive' config param to the plugin state. This removes decorations from the document when it's not `true`.
It anticipates a UI change to allow the active state to be toggled, which will change this param and respond to it by hiding the sidebar UI.
There's no UI to test for this yet, but there are tests in the `createTyperighterPlugin` spec that test to check that decorations are applied to the view, or not.
We've an API to set the plugin to an active/inactive state.
We have a few different configuration params, and PR adds another one, so I've grouped them into a `config` object and added a single, typesafe setter to reduce code duplication.
=> Add an 'isActive' config param to the plugin, and remove decorations when the plugin is not active

src/css/Sidebar.scss, src/css/index.scss, src/ts/components/Controls.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/components/icons/CloseIcon.tsx, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx
We want users to be able to turn Typerighter on and off in the UI so that they can work without distractions. This PR creates that functionality in the UI and links to state, following on from the work in this PR: https://github.com/guardian/prosemirror-typerighter/pull/91.
Run locally and see the button to turn on Typerighter (it is defaulted to 'off' until linked with the store), and then click 'close' icon on the open sidebar to toggle.
The Typerighter UI is hidden when the 'close' icon is clicked and shown when 'open' is clicked.
=> Toggle on off

src/ts/components/Match.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/SidebarMatch.tsx, src/ts/createTyperighterPlugin.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/decoration.ts, src/ts/utils/test/decoration.spec.ts
_co-authored-by: @tjsilver_
At the moment, we assign colours to rule matches in the UI via their categories.
This PR implements a new approach to colours for matches:
- Green: the tool knows this match is correct.
- Orange: the tool is unsure about this match, and would like the user to check it.
- Red: the tool is sure this match isn't correct, and has a replacement.
We can derive these colours from the match state. If a rule doesn't have a replacement, it's Orange; if a rule does have a replacement that's different from the matched text, it's Red; if a rule has a replacement that matches the matched text, it's green.
Before:
After:
Run this plugin locally against text that has all three sorts of matches (for example, this [long …
=> Derive colours for matches

src/ts/components/Match.tsx, src/ts/components/SidebarMatch.tsx, src/ts/utils/decoration.ts, src/ts/utils/test/decoration.spec.ts
This PR reduces the opacity of the ambiguous colour, this reduces the amount of visual noise that Typerighter creates for rules that may be inaccurate. This PR is based on the work done to [change the match colours](https://github.com/guardian/prosemirror-typerighter/pull/95).
Open a document, run the document through Typerighter, observe the amount of visual noise generated by ambiguous rules. 
Users' attention is on matches which are most significant and accurate.
Before:
After:
=> Reduces the opacity of ambiguous decorations

src/ts/components/Match.tsx, src/ts/createTyperighterPlugin.ts, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/test/helpers/prosemirror.ts, src/ts/utils/decoration.ts
Adds an 'ignore matches' predicate that the plugin consumer can supply. This predicate receives every match supplied to the plugin on init or as a result of a successful response. If it returns false, the match is not added to the plugin state.
An example use case at the Guardian: in our text editor, our users have the ability to mark text ranges as 'correct'. We don't want to see matches for these ranges.
The added tests should give us an idea of how this works.
You could also spin this up in a test environment and add a predicate to check it behaves as expected.
Matches that ... match the predicate are not included in the plugin state.
=> Add an 'ignore matches' predicate

src/ts/index.ts, src/ts/state/store.ts
We've added a few predicates/callbacks recently (#94, #88) that require us to reason about plugin interfaces in consumer code. We'll need to export those interfaces so consuming code can use them when defining those predicates.
This is a no-op.
We can access the given interfaces in consumer code.
=> Add interfaces to exports

src/ts/state/reducer.ts
A previous merge seems to have removed the default for this function, which broke the build. This PR fixes that issue.
The build succeeds.
=> Add default colours to `createInitialState`

src/ts/components/Controls.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/state/selectors.ts
At the moment, users must click to activate Typerighter and click again to check a document. Re-activating the plugin without rechecking might be confusing to users. This PR addresses this by keeping the 'Check document' button across open/closed states of typerighter. As soon as 'Check document' is clicked in the closed state, a check is triggered and Typerighter is activated.
Run branch locally and observe that Typerighter carries out a document check when 'Check document' is clicked in the closed state.
Users will find the behaviour intuitive.
=> Trigger search on toggle

build/rollup.config.build.js
This PR fixes the 'remove matches on doc edit' when this plugin is imported.
To do it, it adds the `prosemirror-transform` to externals. This is necessary to fix a subtle bug. When the document changes, we figure out whether the `Step`s generated by the edit change the document in a way that should remove matches:
```ts
tr.steps.filter(
step => step instanceof ReplaceStep || step instanceof ReplaceAroundStep
);
```
However, if we include the library that supplies `ReplaceStep` etc. in our bundle – `prosemirror-transform` – it's then included twice when we import this plugin: once when the third party sets up the editor, and once in our bundle.
This is a problem, because `instanceof` works by comparing prototypes by reference, and we've got two different identities for `ReplaceStep`! The …
=> [Bugfix] Remove matches on doc edit when this plugin is imported

src/ts/components/Results.tsx
Co-authored-by: Sam Hession <samhession@live.co.uk>
The 'fix all' button appeared in the UI although it's not required at the moment. This PR removes it.
Run this branch locally and see that there is no visible 'fix all' button next to 'Results'.
=> Remove 'fix all' button as not required currently

build/rollup.config.build.js, package-lock.json, package.json, pages/index.ts, src/css/MatchDebug.scss, src/css/MatchDecoration.scss, src/css/MatchWidget.scss, src/css/index.scss, src/ts/components/MatchOverlay.tsx, src/ts/createView.tsx
Previously, some ad-hoc position code was being used to position tooltips. This is a hard, edge-casey, solved problem. This PR uses [popper.js](https://popper.js.org/) to solve it instead.
Tooltips should appear underneath match decorations as usual, but now, they're liberated from the bounds of their editor element.
Tooltips are no longer hidden by other DOM elements or constrained by the editor element.
=> Use popper.js to position tooltips properly

build/rollup.config.build.js, package-lock.json, package.json, src/css/MatchWidget.scss, src/modules.d.ts, src/ts/components/Match.tsx, src/ts/utils/dom.ts
Adds markdown to the match descriptions.
Before:
After:
Trigger a match with markdown syntax, like the example. It should be rendered correctly.
Because we don't expect HTML markup, we can avoid using a sanitisation library by stripping HTML from the message data altogether – see `stripHtml`.
=> Add markdown parsing to the match descriptions

src/ts/components/Match.tsx, src/ts/components/SidebarMatch.tsx, src/ts/utils/dom.ts
#115 added markdown for tooltips. But we also have the same markdown in the sidebar 🤦 
This PR adds that.
Before:
After:
You should be able to see markdown in the sidebar match descriptions, as well as the tooltips.
=> Add markdown to sidebar matches, too

src/ts/interfaces/ITelemetryData.ts
Adds a file containing a first pass at some interfaces for telemetry events. These events correspond to user actions that plugin users are likely to find useful in providing actionable information about tool/rule usage.
There's no runtime behaviour yet – implementation will come later once this approach has had some 👀 .
- Do the particular events defined in this PR provide enough information to be actionable, alone or in aggregate?
- Do the more general definitions for `ITelemetryEvent` and `ITyperighterTelemetryEvent` provide interfaces that are extensible enough in the face of future events, or changes to existing events?
We have a set of interfaces that when implemented and sent to a telemetry service provide actionable insights into user behaviour. Questions might include (but are …
=> Add first draft of telemetry interface

src/ts/interfaces/IMatch.ts, src/ts/services/adapters/TyperighterAdapter.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts
Adds rule id to the `IMatch` interface in preparation for our telemetry work.
This is a no-op – the tool should continue to work as expected.
As above.
=> Add rule id to IMatch interface

src/ts/components/Controls.tsx, src/ts/components/Results.tsx, src/ts/components/SidebarMatch.tsx
The Results and SidebarMatch components were React class components. In this PR they have been refactored into functional components. This allows us to use the`useContext` hook and has the additional benefit of removing any deprecated lifecycle methods such as `componentWillMount`.
Run the branch locally and see that the sidebar controls and results work as expected.
=> Refactor more class components

pages/index.ts, src/ts/components/Controls.tsx, src/ts/components/Match.tsx, src/ts/components/SidebarMatch.tsx, src/ts/components/Suggestion.tsx, src/ts/components/SuggestionList.tsx, src/ts/contexts/TelemetryContext.ts, src/ts/createView.tsx, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TelemetryService.ts
We will have an analytics client shortly, responsible for batching and submitting telemetry events. We'd like our Prosemirror plugin to send events when they occur, via that interface.
This PR implements an events service with prosemirror-typerighter that calls the appropriate code when events happen. The backend of the implementation logs to console for now.
Run the branch locally and check the console for details of events triggered. You should see a separate log entry for:
- Checking document
- Using 'close' button
- Clicking on a sidebar match
- Accepting a suggestion
- Marking a match as correct.
=> Set up telemetry service

package-lock.json, package.json, src/ts/commands.ts, src/ts/createView.tsx, src/ts/test/commands.spec.ts, src/ts/test/helpers/createEditor.ts
At the moment, when suggestions are applied to a document, they replace the entire range they're applied to with a new text node. This means that marks that applied to the previous range – e.g. bold styling, or link information – is lost.
This PR copies marks across when they span the whole of the range altered by the selection, preserving them in some, but not all circumstances.
Before
After
This is better, but not quite ideal – marks within the selection that don't cover it will still be lost. For example, the applying the suggestion 'Example' to the text 'exa**mple**' will remove the bold stying, as it doesn't cover the whole range.
We can address this in a follow up PR by diffing the suggested text against what's being replacement, and only applying the above logic to the diff – in …
=> Preserve marks when issuing replacements – step 1

pages/index.ts, src/ts/createView.tsx, src/ts/services/MatcherService.ts, src/ts/services/TyperighterTelemetryAdapter.ts
At the moment, we've no visibility of which matches are made in the document. 
This PR enqueues TYPERIGHTER_MATCH_FOUND events when matches are found in the document, via the [typerighter telemetry service](https://github.com/guardian/prosemirror-typerighter/pull/128). 
1. Run this branch locally
2. Run `ts/add-telemetry-adapter-to-matcherservice` in Composer 
3. Use npm link
4. Check document using Typerighter and watch network requests. You should see requests that include 'TYPERIGHTER_MATCH_FOUND'.
We will receive events in the CELK stack for every Typerighter match found in a document.
We could have done this in one of two ways –
1. Use the UI store subscription to listen for new matches, which will involved writing code to figure out what's new
2. Pass the telemetryService into the …
=> Add Typerighter match telemetry events

.github/workflows/node.js.yml, build/README.md, docs/README.md, package-lock.json, package.json
Adds [semantic-release](https://github.com/semantic-release/semantic-release) via a workflow and [github action](https://github.com/marketplace/actions/action-for-semantic-release). This means automated, semantically versioned releases with nicely formatted release histories 🎉 
In order for semantic release to determine the correct version number, the project requires commits to be compliant with the [commitizen](https://github.com/commitizen-tools/commitizen) format.
This PR adds [git-cz](https://www.npmjs.com/package/git-cz) via a pre-commit githook installed on `npm i` to provide an easy way to format commit messages. You can skip these with `ctrl-c` – you just won't get a release.
Comments on this approach really welcome. I've used it in a personal project and found it very useful. …
=> Add semantic release

pages/index.ts, src/ts/createView.tsx
Manually focuses the editor element when buttons within the match tooltip that relate to the document are clicked – 'mark as correct', and 'apply suggestion'.
If we don't do this, the click unfocuses the editor. As a result, if users press Ctrl-Z to undo the change that's just been made, the Ctrl-Z keyboard event is captured by the browser, not the editor. The browser has its own, divergent opinion about the edit history of the contenteditable managed by the editor, and will produce unpredictable results.
Before:
After:
Make some changes to a document in the editor, run a check, apply a tooltip action, and press Ctrl-Z. The document should undo the tooltip action as expected.
This is difficult to test without browser-based integration tests, which might be worth considering sooner rather …
=> Focus the view when users click tooltip buttons

src/ts/components/Controls.tsx, src/ts/components/Sidebar.tsx, src/ts/services/adapters/TyperighterAdapter.ts
Currently  we manually specify all of the categories Typerighter must check on each request. As a result, the plugin asks for the current categories from the server before it's able to make requests to check documents. Related to this [Typerighter PR](https://github.com/guardian/typerighter/pull/70).
There are two problems with this:
1. there's a wait before you can hit 'Check document' when the plugin starts up
2. if the category list expands whilst the tool is in use, the plugin will miss categories. If it shrinks, the user sees an error.
This PR makes the change to remove category information from the request the plugin makes. 
Run the branch locally (replacing `http://example.com` with the correct `telemetryService` link in `pages/index.ts`).
Check document and see that requests no …
=> Check all categories by default

src/ts/state/selectors.ts, src/ts/state/test/selectors.spec.ts
This PR fixes the loading bar by accounting for the possibility of no categories.
This was an issue introduced by the ability to request a check with no categories, returning all default categories. In these circumstances the request blocks have no category ids associated, breaking how the remaining work percentage is calculated in the selector.
Load the Prosemirror-Typerighter client, make a request, observe the loading bar. It should fill in relation to the matches found.
=> fix: 🐛 Fixes loading bar

src/ts/components/SidebarMatch.tsx, src/ts/components/Suggestion.tsx, src/ts/createView.tsx, src/ts/interfaces/ITelemetryData.ts, src/ts/services/MatcherService.ts, src/ts/services/TyperighterTelemetryAdapter.ts
Add more match information, in tags, to the telemetry data we're sending from prosemirror-typerighter. This is to enable us to filter for matches marked as 'advisory', matches without suggestions, and matches with suggestions in aggregate in our telemetry data. There's also a `markAsCorrect` property we can use to identify 'correct' matches.
It also removes the `matchContext` metric, which is primarily used for detecting bugs and contains data we don't want to retain in telemetry.
Run locally, and take an action that includes a match – accepting a suggestion, marking as correct, clicking in the sidebar. When telemetry events are sent a few seconds later, you should see that they contain the information above.
We can filter for advisory rules, matches without suggestions, 'correct' …
=> Send more match data via telemetry

src/ts/interfaces/IMatch.ts, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts, src/ts/services/adapters/TyperighterAdapter.ts, src/ts/services/adapters/interfaces/ITyperighter.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts
At the moment, our rules don't include the name of their matcher. This will be useful in determining whether rules from different matchers have different telemetry  profiles. This is the sister PR to [this Typerighter PR](https://github.com/guardian/typerighter/pull/77).
Run the branch locally and click `check document`. You will see after a few seconds that `matcherType` appears in the telemetry event request.
We will be able to determine whether rules from different matchers have different telemetry profiles.
=> feat: 🎸 Add matcherType to telemetry 

src/ts/components/Match.tsx
This PR adds the rule id to the "issue with result" feedback link. This should make it easier to identify the rule which has caused the issue.
Submit an issue with a rule, look at the "Technical Context" and observe the rule id has been included.
=> fix: 🐛 Adds the rule id to the feedback form

package.json
`git-cz` is ... too fun by default. This dials back the fun to acceptable levels, that is to say, it is no longer fun.
Take a look at the commit message below and adjust your monocle accordingly.
=> Remove emojis from cz commits

src/ts/state/reducer.ts, src/ts/utils/decoration.ts, src/ts/utils/test/decoration.spec.ts
Height widget decorations are no longer needed since we moved our
[tooltip implementation to Popper.js](#112). Worse still – they cause a bug that prevents users selecting the left hand side of the annotated range.
This PR removes them, and the bug.
Before:
After:
Running the demo locally, attempt to select the left hand side of a matched range.
The selection behaviour above should now be as expected.
=> fix: 🐛 Remove height widget decorations – they're redundant

src/css/Sidebar.scss, src/ts/components/Results.tsx, src/ts/state/selectors.ts
This PR adds the ability to sort Typerighter match results by importance (Red, ambder, green) or in order of appearance in the document. 
Setup  the local Typerighter client, check the document, change the sort order of results. 
Users are able to see the match results in an order that is more appropriate for them.
=> Sort by matches

pages/index.ts, src/ts/commands.ts, src/ts/components/Controls.tsx, src/ts/components/Match.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/components/SidebarMatch.tsx, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx, src/ts/index.ts, src/ts/interfaces/IMatch.ts, src/ts/interfaces/IMatcherAdapter.ts, src/ts/services/MatcherService.ts, src/ts/state/actions.ts, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/store.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/decoration.ts, src/ts/utils/plugin.ts, src/ts/utils/test/decoration.spec.ts
Adds the ability to pass arbitrary filter state, and a filter predicate, to the plugin. Decorations and matches are filtered by the predicate when either the matches or the filter state changes.
This is part 1 of 2 – the next PR will add the UI changes that make altering this state possible.
This is a no-op – the automated tests should pass.
The API looks sane, and the automated tests cover the cases we expect.
This is a large PR! But, don't be alarmed. Most of the changes are related to an interface refactor that's largely ergonomic. 
There are two reasons it's so big –
- Adding another type parameter to the `IPluginState` interface meant a refactor to avoid having to pass `TMatch` and `TFilterState` to almost everything they touched was desirable – most of the time in functions that …
=> Add filter functionality, pt. 1 – add filter state and predicate to plugin state

src/css/Sidebar.scss, src/css/SidebarMatch.scss, src/ts/components/MatchSnippet.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/components/SidebarMatch.tsx, src/ts/components/SidebarMatchContainer.tsx, src/ts/components/SidebarMatchGroup.tsx, src/ts/components/SidebarMatches.tsx, src/ts/index.ts, src/ts/interfaces/IMatch.ts, src/ts/services/adapters/interfaces/ITyperighter.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/component.ts
Before, users could only sort matches by importance (colour). Now the switch ('Summary view') has been adapted so that results are both sorted and matches with the same rule ID are grouped together under a dropdown. 'Summary view' is the default. Grouped matches are indicated by a dropdown arrow and number of matches in brackets. Once the user clicks the dropdown, they will see a short context snippet and the matched text in bold. They can then click on a match and scroll to the match in the document, as for single matches. Users can turn off summary view and the matches will all appear as single matches which are in document order. 
Run the branch locally and experience the expected behaviour outlined above.
Telemetry indicates that users keep summary view switched on and that they are …
=> Group matches by rule ID

src/ts/components/FilterResults.tsx, src/ts/index.ts, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts
Adds a telemetry event for the match filters, FILTER_STATE_CHANGED.
As a small multiplier bonus, exposes the telemetry event interface to the consumer, which I suspect will be handy elsewhere 😁 
Toggle the match filter ... toggles. You should see events emitted by the telemetry service after the usual delay.
We can see when users toggle the match filters in our telemetry. 
Included a minor refactor to DRY up our telemetry service a bit.
=> Add telemetry for filter toggles

src/css/Sidebar.scss
This PR fixes a minor issue with the filter options font size. This size is being overwritten in composer, causing it to display too large. This PR sets the size explicitly fixing the issue. 
before: 
after:
=> fix: Fixes the filter button number size

src/ts/utils/component.ts, src/ts/utils/decoration.ts
This PR aims to fix the scroll-to match issue by tallying up the top offset value until the desired element is found. 
The bug was a result of using `offsetTop` regardless of where the match was found. If for example the match was within a list, the offset would only relative to the top of the list. This would result in the pane scrolling to the top regardless of where the match was located in the document.
There may be a better way of determining the element we want to calculate the offset relative to, using the `ProseMirror` class name seems fraught.
Check a document with various matches, turn a set of matches into a list (or nested list), navigate to those match by using the sidebar. The panel should scroll to the correct location.
=> fix: Fixes the scroll to match issue

src/ts/components/Results.tsx
#153 broke the loading bar, which always appeared at full width. This PR should fix that.
Perform a check. The loading bar should behave as expected.
=> fix: Fix loading bar always appearing at max width

.github/workflows/node.js.yml, .travis.yml, build/README.md, docs/README.md
Closes: #156 #157
Changes references from 'master' branch to 'main' in config and documents, following the renaming of the base branch. Merging this PR will also serve as a test of whether the branch renaming process has worked.
=> chore: Rename master branch to main

src/ts/commands.ts, src/ts/components/MatchOverlay.tsx, src/ts/createTyperighterPlugin.ts, src/ts/state/actions.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/clientRect.ts
This PR handles the placement of popups on matches which cross multiple lines. This is important as previously some match popups would be impossible to reach due to their placement. 
This issue is fixed through the usage of `getClientRects` which provides a set of rectangles which an element covers, importantly with a separate rect per line. When the popup event is triggered on mouseover, the rect index is saved for reference. This is then used when determining the offsets of the popup and adjusting the offset X and Y based on the rect values.
Run a document through TR, find a match which spans multiple lines, observe that it's possible to access a popup regardless of where the match is hovered over.
Users are always able to access a match popup and they are placed in a sensible position. …
=> fix: popover placement issue

build/rollup.config.build.js, package-lock.json, package.json, src/modules.d.ts, src/ts/createTyperighterPlugin.ts, src/ts/state/reducer.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/createEditor.ts, src/ts/utils/decoration.ts, src/ts/utils/prosemirror.ts, src/ts/utils/range.ts, src/ts/utils/test/prosemirror.spec.ts
Adds the ability for a match and its associated decorations to be removed when the user clicks immediately to the left of it (this behaviour already existing for user clicking to the immediate right of a match).
- Locally, check the text: 'We an hope to address it.' You should get a match for 'an'.
- and a `c` to correct 'an' to 'can'. The match should disappear from the document and Typerighter panel.
A match will disappear after the user has typed something immediately next to it, both its decoration in the document and its entry in the Typerighter panel.
=> fix: Remove matches when range edge touched

src/ts/interfaces/IMatch.ts, src/ts/services/MatcherService.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/state/reducer.ts, src/ts/state/store.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/block.ts, src/ts/utils/match.ts, src/ts/utils/prosemirror.ts, src/ts/utils/range.ts, src/ts/utils/test/block.spec.ts, src/ts/utils/test/match.spec.ts, src/ts/utils/test/prosemirror.spec.ts, src/ts/utils/test/range.spec.ts
This PR adds logic to remove skipped ranges from blocks we send to our matcher service, and map returned matches through those ranges.
This was originally [implemented on the server](https://github.com/guardian/typerighter/pull/85), and in the accompanying PR there were a few notes as to why we'd made that choice. This PR effectively moves this logic to the client. 
This is because it's very difficult to debug problems with `skipRanges` logic that spans client and server. At the moment, we produce skipped ranges on the client, pass the block in its entirety to the server with the skippedRanges included, and rely on the server to do the right thing. But, if the server does the _wrong_ thing, it's difficult to understand where the problem lies –
- are the skippedRanges incorrectly placed?
- …
=> feat: Handle skip ranges on the client

pages/index.ts, src/ts/components/MatchOverlay.tsx, src/ts/createTyperighterPlugin.ts, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/utils/decoration.ts
Adds a telemetry event and a callback to enable us to post that event when the match decoration is clicked. Clicking on a match range will send that match's data to the telemetry client.
We _think_, because of historical, workflow-related issues, users are selecting ranges and manually making changes, rather than using the green 'apply suggestion' button in the tooltip. This'll, I hope, help us find out.
You can of course make a cursor selection next to a word without clicking the surrounding span, but my hope is that this will pick up e.g. ~50% of the cases. When I went to select text, I found myself clicking within the span every time, using the bounding box as to orient the cursor, but others' behaviour may well be different.
Users may be annotating a broader range when they make their …
=> feat: add telemetry on match decoration click

src/ts/components/Markdown.tsx, src/ts/components/SidebarMatch.tsx
Memoizes the `SidebarMatch` component, which is continually rerendered as our state changes.
This results in a significant improvement in our JS calc times. Timings taken when rechecking an article of 4,540 (to better isolate unneeded rerenders), averaged over 5 tries:
| Before | After |
|-|-|
| 6252ms | 4234ms |
This is a no-op for features, but the impact is noticeable when using CPU throttling in e.g. Chrome.
=> fix: Memoize SidebarMatch to avoid rerendering as results arrive

src/ts/services/adapters/TyperighterWsAdapter.ts
The server messages for websockets are changing for a better semantic fit. This PR brings the client into line.
The relevant PR on the server side is [here](https://github.com/guardian/typerighter/pull/20) – see the `CheckXYZ` message objects in `/model`. 
Do the client messages match what the server sends?
This is a no-op – we don't use websockets for checks ... yet!
=> fix: Adjust websockets messages to match server

src/ts/state/helpers.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/prosemirror.ts
Changes new DecorationSet() -> DecorationSet.empty, for two reasons:
- new DecorationSet, although it works, isn't documented.
- we think object identity shenanigans may be causing a bug.
This is no-op – everything should work as expected.
=> fix: new DecorationSet() -> DecorationSet.empty

.github/workflows/semantic-PRs.yml
Trigger our pull request linter on the `pull-request` event, not `pull-request-target`, b/c:
... meaning it might possible to open a PR via a fork that ran code to e.g. pull out secrets. I haven't confirmed, but this tighter scope makes sense regardless.
Thanks @akash1810 for spotting!
This is a no-op – our actions should continue to work as expected.
Fewer vulns in our build process.
=> chore: Update semantic-PRs.yml

package-lock.json
Removes and re-adds the `package-lock.json` file from the project to fix a problem with inconsistent `react` and `react-dom` versions, as at the moment they're resolving to `17.0.2` and `16.13.1` respectively.
Run `npm ls react` and `npm ls react-dom` in the project root. `17.0.2` should be the only version that resolves.
=> fix: Remove and re-add package-lock.json to ensure react-dom@17.0.2

src/css/index.scss
Removes redundant tooltip styling. As well as being unnecessary (due to switching to PopperJS #112), the styling is causing placement problems in consumer code at different zoom levels.
You'll need to use `npm link` to use this with your consumer:
```bash
npm link # In prosemirror-typerighter dir
npm link @guardian/prosemirror-typerighter # in consumer project (e.g. Composer)
```
You should see accurate popup placement at non-100% zoom levels. E.g. at 90%:
| before | after |
| --- | --- |
| <img width="335" alt="Screenshot 2021-09-27 at 09 48 14" src="https://user-images.githubusercontent.com/7767575/134875869-afde97ab-e96d-43f4-8b5c-ed9eadae9285.png">|<img width="335" alt="Screenshot 2021-09-27 at 09 48 21" src="https://user-images.githubusercontent.com/7767575/134875858-0ff24637-3a6a-4ef …
=> fix: Remove redundant tooltip styling

src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/utils/range.ts
At the moment, there's a bug in prosemirror-typerighter: shortening the document whilst a match is in flight can cause unexpected behaviour if the match is now outside the bounds of the document.
This is not a crash in our demo, but does cause problems in the Guardian's CMS, where `ignoreMatches` is operating on matches outside of the bounds of the document in ways that cause a crash.
It also results in a bug phantom matches hanging around in our state – the document disappears, but we still accrue matches in this example:
Thanks to @SHession for pointing out the bug!
- The new unit test should pass.
- Attempt to replicate the bug above. It should no longer be possible.
=> fix: Do not allow matches that fall outside of the doc into the plugin state

src/ts/components/Controls.tsx, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/store.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/prosemirror.ts, src/ts/utils/test/prosemirror.spec.ts
Filters the block queries before they're added to our plugin state (and subsequently sent to our checking service) to cull any that are empty.
This should ensure that we don't send requests for ranges with no content.
For good measure, we remove any ranges that just contain whitespace.
- The unit tests should pass, and you should be convinced they handle the scenario above.
- Try hitting removing all of the content in a document in a running demo instance, and hit 'check document'. You should not see a request go out. Contentful documents should issue requests as normal.
No requests for checks that contain empty ranges.
=> fix: Filter block queries to ensure zero-width blocks are not included in requests

src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/helpers/fixtures.ts
When Typerighter's operating in realtime mode (`requestMatchesOnDocModified = true`), it keeps track of dirtied ranges, and ensures that any ranges dirtied whilst a request for that range is in flight invalidate matches made in that request.
In non-realtime mode, it ... doesn't. See #189.
This change corrects that oversight, ensuring that dirtied ranges are tracked whilst requests are in flight. Once the request is complete, `dirtiedRanges` is reset, and ranges are no longer tracked.
- The automated tests should pass, and you should be satisfied they test for the correct behaviour.
- Try to reproduce #189, perhaps by [manually increasing browser latency](https://umaar.com/dev-tips/66-network-throttling-profiles/#:~:text=Go%20to%20Settings%20%3E%20Throttling.,the%20Network%20Panel%20throttl …
=> fix: Keep track of dirty ranges when requests are inflight so they supercede incoming matches

src/ts/services/MatcherService.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/helpers/fixtures.ts
Renames IBlocksInFlightState -> IRequestInFlight, to address the confusion described in #191.
This is a no-op – the library should work as before, and the tests should pass.
=> chore: Rename IBlocksInFlightState -> IRequestInFlight

src/css/index.scss
Adds a z-index to our tooltip container, which ensures that tooltips are raised above sidebar content.
|Before|After|
|--|--|
| <img width="552" alt="Screenshot 2022-01-19 at 13 04 24" src="https://user-images.githubusercontent.com/7767575/150137723-d6abbf5b-d079-4322-92dc-300e5aaf8365.png">|<img width="552" alt="Screenshot 2022-01-19 at 13 04 58" src="https://user-images.githubusercontent.com/7767575/150137690-6737056c-04d0-4695-bf07-bed5c79c366c.png">
Does this PR resolve the visual issues present in 'before', above?
=> fix: Add z-index to correct positioning of tooltips

pages/index.ts, src/ts/createTyperighterPlugin.ts, src/ts/state/reducer.ts, src/ts/test/createTyperighterPlugin.spec.ts
Allows enabling real-time checking when the plugin is instantiated, via the options passed to the plugin creator function.
Previously, this was only possible by dispatching a transaction to alter a configuration option, adding complexity and work.
- I've added a test to check that we're passing the option through.
- Run locally, and begin editing the document. You should see that requests for matches are triggered after modification (the [default throttle is 2000ms](https://github.com/guardian/prosemirror-typerighter/blob/af470ec0741f3ec232004eeea1cf76fd512da92a/src/ts/services/MatcherService.ts#L34)).
=> feat: Allow enabling real-time checking when the plugin is instantiated

pages/index.ts, src/css/Controls.scss, src/ts/components/Controls.tsx, src/ts/components/Sidebar.tsx, src/ts/createView.tsx, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/utils/decoration.ts
Adds a 'dev mode' parameter to the view function, which when `true` presents the user with two checkboxes that permit:
- Turning real-time checking on and off
- Adding annotations to ranges that have pending (orange) or in-flight (green) checks.
Pending checks are only really relevant in real time mode – they represent the ranges that have been 'dirtied' since the last check, and are due to be sent to Typerighter. In-flight checks have been sent to Typerighter and have not yet come back.
Here's how the UI looks:
And here's the annotations at work, with an explanation:
I've defaulted dev mode to true in the sandbox – hopefully that makes sense.
Fire up prosemirror-typerighter locally and have a play. Does it behave as expected? Do you think these things will be useful?
=> feat: Add a 'dev mode' flag to the view, and a few developer utilities

docs/README.md, package.json
Adds instructions for local testing. Cribbed from [prosemirror-elements.](https://github.com/guardian/prosemirror-elements)
Do the instructions make sense? Do they work?
=> chore: Add instructions for local testing

src/ts/components/Results.tsx, src/ts/components/SidebarMatches.tsx, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts, src/ts/state/selectors.ts
Removes the summary toggle. We know from our telemetry that it's no longer used frequently enough to warrant its existence:
|Before|✨After✨|
|-|-|
|<img width="409" alt="Screenshot 2022-07-25 at 13 44 59" src="https://user-images.githubusercontent.com/7767575/180780626-d90e40dc-6c86-46d6-a990-80309c36dc50.png">|<img width="409" alt="Screenshot 2022-07-25 at 13 44 48" src="https://user-images.githubusercontent.com/7767575/180780663-f1a73704-57db-4eeb-bed3-271604b2d74f.png">|
Is the toggle gone? Is any related code cleared out?
=> feat: Remove summary toggle

src/ts/services/TyperighterTelemetryAdapter.ts
This allows applications to pass in optional tags to be added to telemetry events. Examples of tags to be passed in include `contentType`, `contentId`, `documentUrl` and `blockId`.
Using the [instructions in the readme](https://github.com/guardian/prosemirror-typerighter/tree/main/docs#testing-locally-in-applications-that-use-prosemirror-typerighter), point your application (eg composer) to your local version pf prosemirror-typerighter. Pass custom tags into the TyperightTelemetryAdaptor and launch the app locally. Monitor the network traffic in developer tools and see your custom tags appear in the typerighter telemetry events.
=> feat: Add optional tags to Typerighter Telemetry Adaptor

pages/index.ts, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx, src/ts/services/MatcherService.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/createEditor.ts
Co-authored by @jonathonherbert and @ParisaTork 
This PR stops moves the responsibility for creating a MatcherService into `prosemirror-typerighter`, and no longer requires the consuming service to provide a MatcherService.
This simplifies the setup required by the consuming service. The work of providing a matcher service will no longer need to take place within `setupTyperighterView` in consumers, which means that we can run checking from `prosemirror-typerighter` without rendering the UI (e.g. in the liveblog).
This should be a no-op within `prosemirror-typerighter`, but will require some changes in the consumer because of the interface change.
1. Run `prosemirror-typerighter` locally. Does the service run as expected? Do all tests pass?
=> feat!: Provide matcher service, rather than expecting the consumer to provide one

pages/index.ts, src/ts/services/adapters/TyperighterChunkedAdapter.ts, src/ts/services/adapters/test/TyperighterChunkedAdapter.spec.ts
Adds a TyperighterAdapter that handles a chunked response that returns [json-seq](https://en.wikipedia.org/wiki/JSON_streaming#Record_separator-delimited_JSON_2). The counterpart to [this PR](https://github.com/guardian/typerighter/pull/20) in Typerighter.
Reading the stream was more involved than expected, because there is no guarantee that the chunks we read from the stream correspond to complete records – even if (as is explained in the PR above) the server is sending chunks that happen to correspond to complete records. As a result, we maintain a buffer and wait until we see a `RECORD_SEPARATOR` before flushing records to Typerighter.
That chunk-to-record behaviour isn't specified anywhere, and so it's best probably best not to rely on it, anyhow.
- The automated tests should pass. …
=> feat: Add chunked adapter

src/ts/services/MatcherService.ts
A redundant console warn slipped through.
This PR makes it do something more useful.
=> fix: Fix redundant console warn

src/css/Sidebar.scss, src/ts/components/Tooltip.tsx
A small tweak to keep the information icon added in #217 centered in our consuming CMS.
|Before|After|
|-|-|
|<img width="227" alt="Screenshot 2022-08-22 at 14 12 56" src="https://user-images.githubusercontent.com/7767575/185934467-7d1c3184-f63b-487c-a723-e3e24a14cac4.png">|<img width="227" alt="Screenshot 2022-08-22 at 14 37 10" src="https://user-images.githubusercontent.com/7767575/185934501-4020d35b-73b8-4a1c-8fae-1f808645d8b3.png">|
Quite subtle – I've adjusted the position of the icon so it should be dead centre, and removed the gray border above the coloured banner, which in my eyes altered the perception of central-ness for the icon.
Take a look at the screenshots, or run locally. (Test in Composer is possible via the instructions in the readme.) Do you get a sense of ... geometric …
=> fix: Tweak to center info icon

src/css/Sidebar.scss, src/ts/components/Tooltip.tsx, src/ts/utils/decoration.ts
Fixes an issue where as a result of changes in #169, match styling would not apply correctly when matches were broken across lines.
|Before|After|
|-|-|
Previously, we were using the `:after` pseudo element to achieve this effect with a background image. This doesn't play nicely with the [multiple border-boxes that constitute a broken span](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects), but [border-image (TIL!)](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image) does.
One caveat – the green line is some subpixel-width fatter than before, I think as a result of being exactly rather than approximately 3px. I think it's still clear. Sadly, I haven't found a way to make match the previous styling exactly, and the next pixel down looks too thin to me: …
=> fix: Fix styling when correct and default matches span multiple lines

src/ts/utils/decoration.ts
A quick follow up to fix something I didn't spot while testing #225 – the styling for 'correct' matches was stretched with the span width 😱 It's trivial to spot with longer matches.
|Before|After|
|-|-|
|<img width="579" alt="Screenshot 2022-08-24 at 12 32 27" src="https://user-images.githubusercontent.com/7767575/186408461-a8797608-f74e-491c-ab8f-35483df8f622.png">|
This was a result of me misunderstanding the border-image docs, specifically [border-image-slice.](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice) We now sample from a static repeating pattern, which should be nice and robust.
See #225.
=> fix: Another fix for border styles

src/ts/createTyperighterPlugin.ts, src/ts/state/test/helpers.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/utils/range.ts, src/ts/utils/test/range.spec.ts
_co-authored-by_: @ParisaTork 
In prosemirror-typerighter, when real-time checking is turned on, the plugin sometimes does not check parts of the document.
There are two cases I've found – on paste, and when newlines are introduced more quickly than the plugin is configured to send check requests.
There are two phases to a real time check: 1. gathering dirty ranges (ranges that have been changed since the last check), and 2. expanding those ranges and sending them to the checking service.
We expand the ranges that have been dirtied to ensure that we're checking the text around the changes that have been made to the document, and not just the changed text. For example, when adding punctuation, or changing the spelling of a word, we'll want to check the context of those changes. Our rule of …
=> fix: Ensure all ranges are correctly checked when realtime checking is enabled

pages/index.ts, src/ts/commands.ts, src/ts/components/Controls.tsx, src/ts/components/Sidebar.tsx, src/ts/createTyperighterPlugin.ts, src/ts/index.ts, src/ts/state/actions.ts, src/ts/state/reducer.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/store.spec.ts, src/ts/test/commands.spec.ts, src/ts/test/helpers/createEditor.ts, src/ts/test/helpers/fixtures.ts
This PR adds a command to enable or disable Typerighter. This will be initially used in the liveblog, where Typerighter will be enabled (or disabled) via a toggle, after which realtime checks will occur (or stop occurring).
When Typerighter is enabled: 
- a check occurs of the whole document.
- realtime checks will continue to occur if they are enabled.
When Typerighter is disabled:
- all matches are removed
- all pending requests are discarded
- realtime checks will no longer occur
1. Run this repository locally according to the instructions in the readme.
2. Try disabling and enabling Typerighter via the toggle in the local application's UI. Are all of the following true:?
- matches are removed from the UI when Typerighter is disabled.
- no pending matches appear after Typerighter is …
=> feat: Add typerighter enabled command

src/ts/state/test/helpers.spec.ts, src/ts/utils/range.ts
At the moment, in prosemirror-typerighter, removing the entire document leaves matches in place. This isn't right – touching or removing text that contains matches should remove those matches. Here's an example, as spotted by @rebecca-thompson: 
https://user-images.githubusercontent.com/7767575/189712382-d78a008b-3550-4afd-b377-6662c33f2061.mov
This PR fixes that by removing matches that no longer have a width as a result of being mapped through doc changes.
The story for removing ranges in response to document edits is now split between our business-as-usual mapping operations in 1) `getNewStateFromTransaction`, which is called on every transaction, and 2) our `applyNewDirtiedRanges` action, which is dispatched as an additional transaction when the document changes. This is because …
=> fix: Remove matches when they do not have a width

src/ts/index.ts
Exports the chunked adapter introduced in #21. 
Should be straightforward to verify visually, but you could consume this package with `yarn yalc` in e.g. flexible-content if you'd like to verify – see the instructions in the readme.
=> feat: Export chunked adapter

src/ts/commands.ts, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx, src/ts/interfaces/IMatcherAdapter.ts, src/ts/services/MatcherService.ts, src/ts/state/actions.ts, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/plugin.ts
Removes the type parameters from our plugin state.
These were added in anticipation of a changing set of use cases, but add some complexity to the codebase.
Prompted by @rebecca-thompson wondering what they were for,   we don't currently make use of them in consuming code, and so I think it's fair to say the complexity cost now outweighs any future benefit.
We can always add 'em back if needed.
This is a no-op. The automated tests should work. When running the sandbox, `prosemirror-typerighter` should work as usual.
A codebase that's easier to understand.
=> chore: Remove type parameters from plugin state

pages/index.ts, src/ts/commands.ts, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/createTyperighterPlugin.ts, src/ts/createView.tsx, src/ts/index.ts, src/ts/interfaces/IMatcherAdapter.ts, src/ts/services/MatcherService.ts, src/ts/state/actions.ts, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/createEditor.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/plugin.ts
Exports a `getState` function that will return the Typerighter plugin state, given a general `EditorState`, alongside the relevant selectors to get hold of particular bits of plugin state.
This simplifies a few signatures that we export, and makes getting hold of the plugin state from an editor instance simpler in consuming code.
This is a breaking change, as it alters the signature of `boundCommands`.
- The automated tests should pass.
- The use case should make sense!
Consuming code has an easier time accessing an editor's Typerighter state.
=> feat!: Export getState

pages/index.ts, src/ts/commands.ts, src/ts/createTyperighterPlugin.ts, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts, src/ts/services/adapters/TyperighterAdapter.ts
Adds an error event to the telemetry adapter, and triggers it when there is an error fetching matches. Also adds the URL called to the error message.
In the sandbox, trigger an error fetching, perhaps by expiring a cookie or disabling your network connection in your browser developer tools. After a short delay, you should see a network call go out to the event service. It should contain an event that looks a bit like:
```json
[
{
"type": "TYPERIGHTER_ERROR",
"app": "prosemirror-typerighter",
"stage": "DEV",
"tags": {
"message": "https://checker.typerighter.code.dev-gutools.co.uk/checkStream responded with 401"
},
"eventTime": "2022-11-01T08:47:19.195Z"
}
]
```
Better visibility for developers when prosemirror-typerighter has trouble talking to the Typerighter server.
=> feat: Add error event to telemetry

index.html, pages/index.ts, src/ts/utils/decoration.ts
Disable browser spellchecking in matched text.
|Before|After|
|--|--|
|<img width="373" alt="Screenshot 2022-11-07 at 09 31 56" src="https://user-images.githubusercontent.com/7767575/200277941-e74c39ba-46b1-4b84-862f-fba710cb43be.png">|<img width="373" alt="Screenshot 2022-11-07 at 09 32 30" src="https://user-images.githubusercontent.com/7767575/200277950-873184d7-2a66-4d65-bb7b-a16254d9b6a3.png">|
Running locally, and making sure your browser's spellcheck is on, introduce some words to the sandbox that result in a hit from the spellcheck and Typerighter simultaneously ('Keir Starmer' does the trick for the basic spellcheck in Chrome.) They should match the result above.
=> fix: Add spellcheck=false to match decorations

src/ts/components/FilterResults.tsx, src/ts/components/SidebarMatch.tsx, src/ts/components/icons.tsx, src/ts/state/selectors.ts, src/ts/state/test/helpers.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/utils/decoration.ts, src/ts/utils/test/decoration.spec.ts
Match filters are currently represented in the prosemirror-typerighter plugin as HAS_REPLACEMENT, DEFAULT and CORRECT. 
This maps to:
HAS_REPLACEMENT == 'Amend'
DEFAULT == 'Review'
CORRECT == 'Ok'
This is inconsistent with the UI and newbies to the repo would benefit from this refactor, as it makes the codebase easier to understand.
Run Composer and Prosemirror-Typerighter locally - does Typerighter still work?
=> refactor: Refactors match types

src/ts/components/MatchOverlay.tsx, src/ts/components/SidebarMatch.tsx, src/ts/utils/decoration.ts
Adds a double border AMEND match tooltips and sidebar matches.
Here's an example of what that looks like in Composer (click an image for detail):
|Before|After|
|--|--|
|<img width="632" alt="Screenshot 2022-11-30 at 15 29 01" src="https://user-images.githubusercontent.com/7767575/204839467-e70c781c-816c-4520-ba54-5a7df3c820c4.png">|<img width="632" alt="Screenshot 2022-11-30 at 15 29 29" src="https://user-images.githubusercontent.com/7767575/204839488-724abdd4-3a63-4bbc-8246-6c5c9a4dc374.png">|
Running locally or in a consuming app, take a look at some red matches (the sentence, `The style guide at The Guardian.` will give you a red match.) Do they look OK in the document content and the sidebar?
=> feat: Add double border to AMEND match tooltips and sidebar

src/ts/index.ts
Composer will now have it's own copy of the Typerighter sidebar so that UI changes can be iterated upon more quickly. 
This adds extra exports to make that possible.
You don't need to do much other than make sure that this repo can build, following the instructions in the readme.
=> feat: Add additional exports to library so that Composer can use own sidebar

docs/README.md
This PR makes a trivial readme change to trigger a release after some new permissions problems prevented the last release. 
(Re-running[ the action](https://github.com/guardian/prosemirror-typerighter/actions/runs/5948928873) doesn't help because "The local branch main is behind the remote one, therefore a new version won't be published.".)
=> feat: Trivial readme change to trigger release

src/ts/services/adapters/TyperighterChunkedAdapter.ts, src/ts/state/actions.ts
This makes sure that categories passed from Composer are included in the match request to the Typerighter Checker service, where they can be used to filter matches,
Test locally with [this Composer branch](https://github.com/guardian/flexible-content/pull/4391) via `yalc` (I can pair to help with this, it's a bit fiddly) - also run this branch of [Typerighter](https://github.com/guardian/typerighter/pull/413) Checker locally.
Good things to check:
- Does Typerighter work as expected?
- If no categories are provided, are all matches returned, regardless of category? (This is the intended behaviour).
- If a category is provided, are only matches with that category returned?
=> feat!: Pass categories through to backend

.github/workflows/snyk.yml
Update the snyk org so it's reporting to the right place (this will report to the "test" org rather than ed-tools. See: https://github.com/guardian/prosemirror-typerighter/pull/223/files#diff-279a5a5997dd6e7a67267df6229cd45adb7acdb39c8ebab573f98e524deb0fd5R13
Proper vulnerability monitoring of this repository.
=> ci: Fix snyk config

src/ts/components/Match.tsx
This PR makes sure that more than just the first suggested replacement word is shown for Collins dictionary rules. The first suggestion will still appear when users hover over an underlined word. When there is more than one suggestion, a 'See more suggestions' button will appear, which users can click to see additional suggested words.
Before this, only the first dictionary rule suggestion was being shown.
This can be tested locally using [`yalc`](https://github.com/guardian/prosemirror-typerighter#testing-locally-in-applications-that-use-prosemirror-typerighter) to locally publish this branch's version of prosemirror-typerighter and to run this package in Composer.
Steps to test:
- create an article
- add a Collins dictionary misspelled word e.g. 'primery' - after running Typerighter you …
=> fix: Show multiple suggestions for dictionary rules

src/ts/commands.ts, src/ts/test/commands.spec.ts
Fixes a bug where Prosemirror will throw an error if commands are dispatched after the editor is destroyed.
This PR solves the immediate problem, but it'd be nice to cancel the relevant fetches when the document is destroyed to avoid redundant work.
The automated test for this case should pass. We should also see the related [Sentry errors](https://the-guardian.sentry.io/issues/3686433779/?project=26737&query=&referrer=project-issue-stream) drop off once Composer uses this release.
=> fix: Do not throw an error when a command is dispatched and the document has been destroyed

src/ts/interfaces/IMatch.ts, src/ts/services/adapters/interfaces/ITyperighter.ts, src/ts/services/test/MatcherService.spec.ts, src/ts/state/test/reducer.spec.ts, src/ts/state/test/selectors.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/test/helpers/fixtures.ts, src/ts/utils/test/match.spec.ts
Makes `groupKey` available to the typerighter client. 
This is the glue needed between [this PR](https://github.com/guardian/typerighter/pull/436) (where `groupKey` is introduced) and [this PR](https://github.com/guardian/flexible-content/pull/4396) (where `groupKey` is consumed by the client).
Once this change goes in, we'll need to bump the version of `prosemirror-typerighter` in https://github.com/guardian/flexible-content/pull/4396.
Difficult to test in isolation beyond making sure the unit tests still pass.
=> feat: Add `groupKey` to `IMatch`

pages/index.ts, src/css/Feedback.scss, src/css/MatchWidget.scss, src/css/index.scss, src/ts/components/Feedback.tsx, src/ts/components/Match.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/createOverlayView.tsx, src/ts/interfaces/ITelemetryData.ts, src/ts/services/TyperighterTelemetryAdapter.ts
Adds a little form for inline feedback, replacing the Google form in that context. (The Google form remains for general tool feedback in the sidebar, for now.)
Have a play. Does the form work as expected? Any styling or messaging we could improve?
More feedback from users, as a result of a streamlined feedback experience.
=> feat: Add match feedback inline

package-lock.json, package.json, src/ts/components/Controls.tsx, src/ts/components/MatchOverlay.tsx, src/ts/components/Results.tsx, src/ts/components/Sidebar.tsx, src/ts/createTyperighterPlugin.ts, src/ts/state/helpers.ts, src/ts/state/reducer.ts, src/ts/state/selectors.ts, src/ts/state/store.ts, src/ts/state/test/reducer.spec.ts, src/ts/test/createTyperighterPlugin.spec.ts, src/ts/utils/shallowEqual.ts
Doing some performance profiling in the Guardian's CMS, Composer, it looks like we’re spending a lot of time rendering Typerighter’s UI, even when it’s not onscreen and there are no matches to display.
This is because the Typerighter plugin store is emitting events on every state update, even when nothing's changed.
Rather than burden the consumer with this check, this PR solves the problem at source for empty documents. When the plugin view updates, we now check to see if the plugin state has changed before updating store subscribers. This helps reduce unnecessary rerenders when subscribers are rendering UI in response to state changes.
The best way would be to run a reference check: `prevState === state`. Unfortunately, we always update dirty ranges when the document changes, although …
=> fix: Only update consumers when state changes
