jest.config.js
pages/dist/bundle.js
pages/dist/styles.css
src/ts/components/ValidationControls.tsx
src/ts/index.ts
src/ts/state.ts
src/ts/test/helpers/prosemirror.ts
src/ts/test/prosemirror.spec.ts
src/ts/test/state.spec.ts
src/ts/test/validationAPIService.spec.ts
src/ts/utils/prosemirror.ts
src/ts/view.tsx

Create 'validate whole document' action

---

LICENSE.md
NOTICE.md
docs/README.md
pages/dist/bundle.js
pages/index.ts

Update the readme to reflect the latest changes, and the license files to keep the project in line with Guardian standards.

Update readme and license

---

pages/dist/bundle.js
pages/dist/styles.css
pages/index.ts
src/css/validation.scss
src/ts/createValidationPlugin.ts

Fixed an issue where the passed getState command wasn't bound to the plugin instance.

Fix bind bug

---

src/ts/commands.ts
src/ts/state.ts
src/ts/test/state.spec.ts
src/ts/utils/array.ts

Moves some of the apply suggestion logic out to a selector, which is easy to test.

Simplify apply suggestion command

---

package.json
pages/dist/bundle.js
src/ts/commands.ts
src/ts/state.ts
src/ts/test/helpers/prosemirror.ts
src/ts/test/prosemirror.spec.ts
src/ts/test/range.spec.ts
src/ts/test/state.spec.ts
src/ts/test/store.spec.ts
src/ts/utils/prosemirror.ts
src/ts/utils/range.ts
travis.yml

This PR addresses a few admin-y todos, mostly related to test coverage and unused code, and adds a bunch more tests for good measure so I don't feel bad when the coverage badge is eventually added to the readme.

Address todo refactors

---

src/ts/store.ts

DRYs up some typing boilerplate.

Cleaner types for the store

---

rollup.config.js
src/css/sidebar.scss
src/css/validation.scss
src/css/validationControls.scss
src/css/validationSidebarOutput.scss
src/ts/components/ValidationOutputContainer.tsx
src/ts/components/ValidationOverlay.tsx
src/ts/components/ValidationSidebarOutput.tsx
src/ts/index.ts
src/ts/interfaces/IValidation.ts
src/ts/services/adapters/interfaces/ITyperighter.ts
src/ts/services/adapters/languageTool.ts
src/ts/services/adapters/typerighter.ts
src/ts/test/helpers/fixtures.ts
src/ts/test/state.spec.ts
src/ts/test/validationAPIService.spec.ts
src/ts/utils/decoration.ts

Some styling fixes and refinements. Notably:
- There's a category property added to ValidationOutput. It has a colour, which informs the UI.
- A bounding issue with the hover overlay has been fixed.
- A few minor tweaks to remove errant borders etc.

Style fixes/refinements

---

src/ts/services/ValidationAPIService.ts

This PR fixes an issue where the validation service provider could become stuck in a pending state.

Stuck validation state

---

rollup.config.js

Add sourcemaps to gh-pages/dev page

---

pages/index.ts
src/ts/components/Sidebar.tsx
src/ts/createView.tsx

... so we don't have to check in internal e-mail addresses 😁

Parameterise the sidebar e-mail address 

---

build/README.md
package.json

Adds additional documentation improves commands to clarify processes for development and release.
The commands in the NPM scripts should work as expected.
If the docs give enough guidance for new devs to be able to confidently run the project locally and issue releases.

Improve developer experience via docs, npm commands

---

package-lock.json
package.json

Reverts guardian/prosemirror-typerighter#99

Revert "v1.0.0"

---

build/README.md
src/ts/utils/decoration.ts

A few minor issues need fixing before we release `v1.0.0`:
- the instructions for release weren't clear
- there was a type error in a spec which wasn't caught in a previous merge
The build should pass, and the docs should be slightly clearer.

Update readme and fix issue with spec

---

package-lock.json
package.json

Reverts guardian/prosemirror-typerighter#100

Revert "Revert "v1.0.0""

---

pages/index.ts
src/css/index.scss
src/ts/components/Match.tsx
src/ts/components/MatchOverlay.tsx
src/ts/components/icons/Correct.tsx
src/ts/createView.tsx

This PR adjusts the styling for the "Mark as correct" option (formally ignore match). It moves the functionality from an icon in the bottom left corner, to where the suggestions are normally displayed. 
Check a document for matches, hover over a match, observe the "Mark as correct" option and behaviour.
Users can easily and intuitively dismiss a match by confirming it's correct.
After:
Before:

Mark as correct

---

src/ts/components/Controls.tsx

Co-authored-by: Jonathon Herbert <jonathon.herbert@guardian.co.uk>
The Controls component was class component using a deprecated lifecycle method. In this PR it is changed to a functional component.
Run branch locally and checking the document should work as before.

refactor controls to a functional component

---

src/css/Controls.scss
src/css/Sidebar.scss
src/css/index.scss
src/ts/components/Results.tsx
src/ts/state/selectors.ts

Adds minor styling improvements: 
- Move opinions about sidebar borders outside of view component
- Ensure button's 'disabled' state is clear in consuming views
- Add shimmer to loading bar
Fire up the UI. Does it correspond with the improvements above?
Users should detect a marginal increase in fanciness.

Minor styling improvements 💅

---

src/ts/components/MatchOverlay.tsx

This PR adds a small delay to the match popover to make navigating the document easier. This change was based on feedback provided from users that the popover we interfering with their regular work and would mean they would have to disable Typerighter to continue their usual work. 
Navigate through a Typerighter annotated document, the popovers should not inhibit your ability to make changes.
Users are able to leave Typerighter enabled whilst editing the document.
This delay could cause a minor inconvenience to users and may require some fine tuning.

feat: Adds debounce to match hover

---

build/typedoc.js

Using this repo as inspiration for adding typedoc to a project and the indents were making my eyes twitch.
n/a
no-op
n/a
n/a

chore: Update typedoc.js

---

src/css/index.scss
src/ts/components/FilterResults.tsx
src/ts/components/Match.tsx
src/ts/components/SidebarMatch.tsx
src/ts/components/SidebarMatches.tsx
src/ts/components/icons.tsx
src/ts/utils/decoration.ts
src/ts/utils/squiggle.ts
src/ts/utils/test/decoration.spec.ts

feat: address snagging (beta merge)

---

src/ts/state/reducer.ts

ronseal.gif??
Thanks @Fweddi for the spot!

chore: Remove unnecessary alias

---

.gitignore
docs/README.md
setup.sh

The `./setup.sh` script wasn't working as it was failing to find the nginx mapping. This PR fixes the script and updates the README with up-to-date instructions on getting this project running locally.
Run the set-up script and it should find the nginx mapping file.

chore: Fix setup script to run project locally

---

package-lock.json
package.json
src/ts/components/Controls.tsx
src/ts/components/Match.tsx
src/ts/components/Results.tsx
src/ts/components/SidebarMatchGroup.tsx
tsconfig.json
vite.config.ts

This PR bumps material-ui, paving the road for it to work correctly with emotion in #169. It should be a no-op.
A spin off of #169 to slim down that PR.
Take a look at the UI. Do the material-ui components still work as expected?

chore: Update material UI to fix problem with switch component

---

vite.config.ts

It adds sourcemaps to prosemirror-typerighter build.
Run 'npm run build'. Do the source map files appear alongside the source files in dist?

feat: Add sourcemaps to prosemirror-typerighter build

---

docs/README.md

See previous PR: https://github.com/guardian/prosemirror-typerighter/pull/257

feat: Trivial change to release categories change

---

docs/README.md

See #269. I think this is why we use changesets 😅

feat: Trivial readme change to trigger release #2

---

package-lock.json

chore: Resolving dependabot issues
